### PR TITLE
Initial commit for frontend

### PR DESCRIPTION
**Pull request by katerinapat**
Adding the initial structure for the frontend.
in order to run the frontend locally, please read the instruction in README.md

### CODE REVIEW

**Comment by katerinapat** [comment]
@droslean, I have no permission to add you as a reviewer

**Comment by droslean** [comment]
Great! Can you move it to `cmd/frontend` ? Also feel free to come up with another name as well.

**Comment by katerinapat** [comment]
Moved! For now `frontend` sounds pretty good as it is straightforward what the folder contains   :)

**Comment by droslean** [comment]
OK! so let's move it to `cmd/frontend` then.

**Pull request merged**
